package au.net.nicksifniotis.amedatest.Messages;

import android.os.Message;

/**
 * Created by Nick Sifniotis on 26/09/16.
 *
 * Enumeration class for messages generated by activities that use the AMEDA device.
 * As far as I'm aware, there's only one such message - SEND.
 */
public enum ActivityMessage
{
    TIMEOUT_ABORT,      // Terminate the connection because the AMEDA is misbehaving.
    SEND;               // Sends a packet to the AMEDA device.


    /**
     * Returns the message code that corresponds to the message that has been received.
     *
     * @param msg The message recevied from the messenger.
     * @return The message code.
     */
    public static ActivityMessage Message (Message msg)
    {
        return ActivityMessage.values()[msg.what];
    }


    /**
     * Get the stringy representation of this message.
     *
     * @param msg The message to stringify.
     * @return The string.
     */
    public static String toString(Message msg)
    {
        return Message(msg).toString();
    }
}
