package au.net.nicksifniotis.amedatest.Messages;

import android.os.Message;

/**
 * Created by Nick Sifniotis on 26/09/16.
 *
 * Enumeration class for messages generated by implementations of the Connection interface.
 */
public enum ConnectionMessage
{
    RCVD,
    XMIT,                       // Sent to virtual device to request transmission of data.
    SHUTDOWN,                   // Sent to virtual device to force a shut down.
    CONNECTED,                  // Send to manager - connection established
    DISCONNECTED,               // Sent to manager - connection has been closed down.
    MESSENGER_READY,            // Sent to manager - messenger object is ready.
    CONNECT,
    DISCONNECT,
    CONNECT_FAILED;             // Sent to manager to indicate connection unsuccessful.


    /**
     * Returns the message code that corresponds to the message that has been received.
     *
     * @param msg The message recevied from the messenger.
     * @return The message code.
     */
    public static ConnectionMessage Message (Message msg)
    {
        return ConnectionMessage.values()[msg.what];
    }


    /**
     * Get the stringy representation of this message.
     *
     * @param msg The message to stringify.
     * @return The string.
     */
    public static String toString(Message msg)
    {
        return Message(msg).toString();
    }
}
