package au.net.nicksifniotis.amedatest.Messages;

import android.os.Message;

/**
 * Created by Nick Sifniotis on 26/09/16.
 *
 * Enumeration class containing messages that are generated by the connection manager.
 *
 */
public enum ManagerMessage
{
    // The set of response codes that the device returns to activities.
    READY,                  // Device signalling that it's ready for next instruction.
    CANNOT_MOVE,            // Something is obstructing the wobble board.
    NO_RESPONSE_ANGLE,      // Failed to read angle.
    CALIBRATION_FAIL,       // Failed to calibrate correctly.
    WOBBLE_NO_RESPONSE,     // Wobble board has lost power.
    ANGLE,                  // Received angle - attached as a double value.

    // Other messages that may be sent.
    XMIT,                   // instruct the connection to transmit an instruction
    RCVD,                   // inform the activity that a response has been received
    CONNECTION_DROPPED,     // inform the activity that the connection has been lost
    CONNECTION_RESUMED,     // inform the activity that the connection is (re)established
    CONNECT,                // instruct the connection to try connecting
    DISCONNECT,             // instruct the connection to disconnect
    SHUTDOWN;               // instruct the connection manager to shut down the connection.


    /**
     * Returns the message code that corresponds to the message that has been received.
     *
     * @param msg The message recevied from the messenger.
     * @return The message code.
     */
    public static ManagerMessage Message (Message msg)
    {
        return ManagerMessage.values()[msg.what];
    }


    /**
     * Get the stringy representation of this message.
     *
     * @param msg The message to stringify.
     * @return The string.
     */
    public static String toString(Message msg)
    {
        return Message(msg).toString();
    }
}
