package au.net.nicksifniotis.amedatest.Messages;

import android.os.Message;


/**
 * Created by Nick Sifniotis on 26/09/16.
 *
 * Message class for messages generated by the virtual AMEDA device.
 */
public enum VirtualAMEDAMessage
{
    INSTRUCTION,            /* Sending an instruction packet to the connection */
    MESSENGER_READY;        /* Signals to the connection that my messenger is ready to receive */


    /**
     * Creates a new instance of a message, of whatever type I am.
     *
     * @return The new message.
     */
    public Message Create()
    {
        return BaseMessage.Create(this.ordinal());
    }


    /**
     * Creates a new instance of a message, and attach an AMEDAResponse to it.
     *
     * @param response The AMEDA response to attach to the message.
     * @return The new message.
     */
    public Message Create(String response)
    {
        return BaseMessage.Create(this.ordinal(), response);
    }


    /**
     * Returns the message code that corresponds to the message that has been received.
     *
     * @param msg The message recevied from the messenger.
     * @return The message code.
     */
    public static VirtualAMEDAMessage Message (Message msg)
    {
        return VirtualAMEDAMessage.values()[msg.what];
    }


    /**
     * Returns the payload attached to this message, as a string.
     *
     * @param msg The message to interpret.
     * @return A stringy payload.
     */
    public static String Payload(Message msg)
    {
        return (String) msg.obj;
    }


    /**
     * Get the stringy representation of this message.
     *
     * @param msg The message to stringify.
     * @return The string.
     */
    public static String toString(Message msg)
    {
        return Message(msg).toString();
    }
}
